train_model:
  XGBRegressor:
    learning_rate:
    - 0.01
    - 0.1
    max_depth:
    - 5
    - 8
    n_estimators:
    - 100
    - 200
    booster:
    - gbtree
  AdaBoostRegressor:
    n_estimators:
    - 50
    - 150
    learning_rate:
    - 0.01
    - 0.1
base_model_score: '0.923627241789596'
