columns:
  - ID: string
  - Project Code: string
  - 'PQ #': string
  - 'PO / SO #': string
  - 'ASN/DN #': string
  - Item Description: string

  - Country: string
  - Managed By: string
  - Fulfill Via: string
  - Vendor INCO Term: string
  - Shipment Mode: string
  - Product Group: string
  - Sub Classification: string
  - Vendor: string
  - Molecule/Test Type: string
  - Brand: string
  - Dosage: string
  - Dosage Form: string
  - Manufacturing Site: string
  - First Line Designation: binary  

  - PQ First Sent to Client Date: datetime
  - PO Sent to Vendor Date: datetime
  - Scheduled Delivery Date: datetime
  - Delivered to Client Date: datetime
  - Delivery Recorded Date: datetime

  - Line Item Quantity: integer
  - Line Item Value: float
  - Pack Price: float
  - Unit Price: float
  - Weight (Kilograms): float
  - Freight Cost (USD): float
  - Line Item Insurance (USD): float
  - Unit of Measure (Per Pack): float


drop_columns:
  - ID
  - Project Code
  - 'PQ #'
  - 'PO / SO #'
  - 'ASN/DN #'
  - PQ First Sent to Client Date
  - PO Sent to Vendor Date
  - Item Description

# We will list these columns thinking of that we have dropped the columns we wanted..
numerical_columns:
  - Line Item Quantity
  - Pack Price
  - Unit Price
  - Weight (Kilograms)
  - Unit of Measure (Per Pack)

categorical_columns:
  - Country
  - Managed By
  - Fulfill Via
  - Vendor INCO Term
  - Shipment Mode
  - Product Group
  - Sub Classification
  - Vendor
  - Molecule/Test Type
  - Brand
  - Dosage
  - Dosage Form
  - Manufacturing Site

datetime_columns:
  - Scheduled Delivery Date
  - Delivered to Client Date
  - Delivery Recorded Date


binary_columns:
  - First Line Designation  # To be encoded into binary (0/1)

one_hot_columns:
  - Country
  - Shipment Mode
  - Vendor INCO Term
  - Product Group
  - Sub Classification


creating_target_columns:
  - Line Item Value
  - Freight Cost (USD)
  - Line Item Insurance (USD)


non_numeric_to_handle_columns:
  - Weight (Kilograms)
 

target_column: Shipment Price  # Define the target explicitly

