name: Shipment CI/CD Workflow

on:
  push:
    branches:
      - shipment_branch
    paths-ignore:
      - 'README.md'

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  REPOSITORY_NAME: shipment
  IMAGE_TAG: latest

jobs:

  build-and-push-ecr-image:
    name: Build and Push Docker Image to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::<ACCOUNT_ID>:role/<GITHUB_OIDC_ROLE>
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker image URI
        id: image
        run: echo "IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/${{ env.REPOSITORY_NAME }}:${{ env.IMAGE_TAG }}" >> $GITHUB_ENV

      - name: Build Docker Image
        run: docker build -t $IMAGE_URI .

      - name: Push Docker Image to ECR
        run: docker push $IMAGE_URI

  deployment:
    name: Deploy to EC2
    needs: build-and-push-ecr-image
    runs-on: [self-hosted, linux]

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::<ACCOUNT_ID>:role/<GITHUB_OIDC_ROLE>
          aws-region: ${{ env.AWS_REGION }}


      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker image URI
        run: echo "IMAGE_URI=123456789012.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.REPOSITORY_NAME }}:${{ env.IMAGE_TAG }}" >> $GITHUB_ENV

      - name: Pull Latest Image from ECR
        run: docker pull $IMAGE_URI

      # - name: Stop and Remove Existing Container (if running)
      #   run: |
      #     docker stop shipment_container || true
      #     docker rm shipment_container || true

      - name: Run New Container
        run: |
          docker run -d --name shipment_container -p 8080:8080 $IMAGE_URI

      - name: Final Cleanup (Safe)
        run: |
          docker image prune -f
          docker builder prune -f
